/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CacheConfig {
  policy: string
  capacity: number
}
export interface CacheStatsJs {
  hits: number
  misses: number
  capacity: number
  size: number
}
export declare class Cache {
  get(key: string): unknown
  set(key: string, value: unknown, ttlMs?: number | undefined | null): unknown
  delete(key: string): boolean
  clear(): void
  stats(): CacheStatsJs
  keys(): Array<string>
}
export declare class CacheManager {
  constructor()
  createCache(name: string, config: CacheConfig): Cache
  getCache(name: string): Cache | null
  deleteCache(name: string): boolean
  clear(): void
}
